version: '3'

services:
  generator:
    image: localhost:57000/dotnetcore-gen:ci-${GENERATOR_BUILD_NUMBER-12}
    ports:
      - "${PORT_GENERATOR-8080}:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "${PORT_MAILHOG-8081}:8025"